### ISSUE TITLE
抛出SIGSEGV直接崩溃，无法获取堆栈信息

### ISSUE THREAD

**Issue by kiss718867** [wangshengyang1996/CrashCatcher#1]

**Comment by kiss718867** [comment]
```
2022-11-03 11:42:56.359  7884-7884  AndroidRuntime          com.wsy.crashcatcher                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.wsy.crashcatcher, PID: 7884
                                                                                                    java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:402)
                                                                                                    	at android.view.View.performClick(View.java:7317)
                                                                                                    	at android.view.View.performClickInternal(View.java:7291)
                                                                                                    	at android.view.View.access$3600(View.java:838)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28247)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397)
                                                                                                    	at android.view.View.performClick(View.java:7317) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7291) 
                                                                                                    	at android.view.View.access$3600(View.java:838) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28247) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                                    	at android.os.Looper.loop(Looper.java:219) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
                                                                                                    Caused by: java.lang.StackOverflowError: stack size 8192KB
                                                                                                    	at com.wsy.crashcatcher.MainActivity.nativeCrash(Native Method)
                                                                                                    	at com.wsy.crashcatcher.MainActivity.crash(MainActivity.java:48)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397) 
                                                                                                    	at android.view.View.performClick(View.java:7317) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7291) 
                                                                                                    	at android.view.View.access$3600(View.java:838) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28247) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                                    	at android.os.Looper.loop(Looper.java:219) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
```
抛出 StackOverflowError
